In [16]:
import torch.nn as nn
import torch

In [14]:
l = nn.Linear(2,5)
v = torch.FloatTensor([1,2])
l(v)

tensor([ 1.0033, -1.0780,  0.2147, -0.5529, -0.4722], grad_fn=<AddBackward0>)

In [4]:
s = nn.Sequential(nn.Linear(2,5),nn.ReLU(),nn.Linear(5,20),nn.ReLU(), nn.Linear(20,10), nn.Dropout(p=0.3),nn.Softmax(dim=1))
s

Sequential(
  (0): Linear(in_features=2, out_features=5, bias=True)
  (1): ReLU()
  (2): Linear(in_features=5, out_features=20, bias=True)
  (3): ReLU()
  (4): Linear(in_features=20, out_features=10, bias=True)
  (5): Dropout(p=0.3, inplace=False)
  (6): Softmax(dim=1)
)

In [5]:
s(torch.FloatTensor([[1,2]]))

tensor([[0.0984, 0.1395, 0.1350, 0.0663, 0.0837, 0.0847, 0.0984, 0.1160, 0.0984,
         0.0795]], grad_fn=<SoftmaxBackward>)

In [15]:
l.weight

Parameter containing:
tensor([[ 0.6117,  0.5221],
        [-0.6259, -0.5776],
        [-0.2628,  0.2311],
        [-0.2805,  0.1633],
        [ 0.3672, -0.5272]], requires_grad=True)

# Loss functions