# Tensors

In [2]:
import torch
import numpy as np

In [3]:
a = torch.FloatTensor(3,2)
a

tensor([[ 0.0000e+00, -8.5899e+09],
        [-3.2964e-04,  3.6902e+19],
        [-9.5539e-23,  4.5799e-41]])

In [4]:
a.zero_()

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [5]:
torch.FloatTensor([[1,2,3],[3,2,1]])

tensor([[1., 2., 3.],
        [3., 2., 1.]])

In [6]:
n = np.zeros(shape=(3,2))

In [7]:
n

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [8]:
b = torch.tensor(n)
b

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [9]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [10]:
s = a.sum()
s

tensor(6)

In [11]:
s.item()

6

In [12]:
torch.tensor(1)

tensor(1)

In [13]:
a = torch.FloatTensor([2,3])
a

tensor([2., 3.])